import { createLookupTableResolver } from '@masknet/shared-base';
import {
    AlphaWalletAdapter,
    AlphaWalletName,
    AvanaWalletAdapter,
    AvanaWalletName,
    BitKeepWalletAdapter,
    BitKeepWalletName,
    BitpieWalletAdapter,
    BitpieWalletName,
    CloverWalletAdapter,
    CloverWalletName,
    Coin98WalletAdapter,
    Coin98WalletName,
    CoinbaseWalletAdapter,
    CoinbaseWalletName,
    CoinhubWalletAdapter,
    CoinhubWalletName,
    FractalWalletAdapter,
    FractalWalletName,
    HuobiWalletAdapter,
    HuobiWalletName,
    HyperPayWalletAdapter,
    HyperPayWalletName,
    KeystoneWalletAdapter,
    KeystoneWalletName,
    KrystalWalletAdapter,
    KrystalWalletName,
    LedgerWalletAdapter,
    LedgerWalletName,
    MathWalletAdapter,
    MathWalletName,
    NekoWalletAdapter,
    NekoWalletName,
    NightlyWalletAdapter,
    NightlyWalletName,
    NufiWalletAdapter,
    NufiWalletName,
    OntoWalletAdapter,
    OntoWalletName,
    ParticleAdapter,
    ParticleName,
    PhantomWalletAdapter,
    PhantomWalletName,
    SafePalWalletAdapter,
    SafePalWalletName,
    SaifuWalletAdapter,
    SaifuWalletName,
    SalmonWalletAdapter,
    SalmonWalletName,
    SkyWalletAdapter,
    SkyWalletName,
    SolflareWalletAdapter,
    SolflareWalletName,
    SolongWalletAdapter,
    SolongWalletName,
    SpotWalletAdapter,
    SpotWalletName,
    TokenaryWalletAdapter,
    TokenaryWalletName,
    TokenPocketWalletAdapter,
    TokenPocketWalletName,
    TorusWalletAdapter,
    TorusWalletName,
    TrezorWalletAdapter,
    TrezorWalletName,
    TrustWalletAdapter,
    TrustWalletName,
    UnsafeBurnerWalletAdapter,
    UnsafeBurnerWalletName,
    WalletConnectWalletAdapter,
    WalletConnectWalletName,
    XDEFIWalletAdapter,
    XDEFIWalletName,
} from '@solana/wallet-adapter-wallets';

export const resolveSolanaWalletAdapter = createLookupTableResolver(
    {
        [AlphaWalletName]: AlphaWalletAdapter,
        [AvanaWalletName]: AvanaWalletAdapter,
        [BitKeepWalletName]: BitKeepWalletAdapter,
        [BitpieWalletName]: BitpieWalletAdapter,
        [CloverWalletName]: CloverWalletAdapter,
        [Coin98WalletName]: Coin98WalletAdapter,
        [CoinbaseWalletName]: CoinbaseWalletAdapter,
        [CoinhubWalletName]: CoinhubWalletAdapter,
        [FractalWalletName]: FractalWalletAdapter,
        [HuobiWalletName]: HuobiWalletAdapter,
        [HyperPayWalletName]: HyperPayWalletAdapter,
        [KeystoneWalletName]: KeystoneWalletAdapter,
        [KrystalWalletName]: KrystalWalletAdapter,
        [LedgerWalletName]: LedgerWalletAdapter,
        [MathWalletName]: MathWalletAdapter,
        [NekoWalletName]: NekoWalletAdapter,
        [NightlyWalletName]: NightlyWalletAdapter,
        [NufiWalletName]: NufiWalletAdapter,
        [OntoWalletName]: OntoWalletAdapter,
        [ParticleName]: ParticleAdapter,
        [PhantomWalletName]: PhantomWalletAdapter,
        [SafePalWalletName]: SafePalWalletAdapter,
        [SaifuWalletName]: SaifuWalletAdapter,
        [SalmonWalletName]: SalmonWalletAdapter,
        [SkyWalletName]: SkyWalletAdapter,
        [SolflareWalletName]: SolflareWalletAdapter,
        [SolongWalletName]: SolongWalletAdapter,
        [SpotWalletName]: SpotWalletAdapter,
        [TokenaryWalletName]: TokenaryWalletAdapter,
        [TokenPocketWalletName]: TokenPocketWalletAdapter,
        [TorusWalletName]: TorusWalletAdapter,
        [TrezorWalletName]: TrezorWalletAdapter,
        [TrustWalletName]: TrustWalletAdapter,
        [UnsafeBurnerWalletName]: UnsafeBurnerWalletAdapter,
        [WalletConnectWalletName]: WalletConnectWalletAdapter,
        [XDEFIWalletName]: XDEFIWalletAdapter,
    } as unknown as Record<string, typeof CoinbaseWalletAdapter>,
    null,
);
