project_id: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files: # Paths to the source and translation files
  - source: /src/locales/en/*
    translation: /src/locales/%two_letters_code%/%original_file_name%
