packages:
    - 'packages/*'
    - 'src/maskbook/'
    - 'src/maskbook/packages/*'
    - 'src/maskbook/packages/typed-message/base'
    - 'src/maskbook/packages/typed-message/react'
    - 'src/maskbook/packages/plugins/*'
    - 'src/maskbook/packages/polyfills/types'
    - 'src/maskbook/packages/web3-hooks/base'
    - 'src/maskbook/packages/web3-hooks/evm'
    - 'src/maskbook/packages/web3-shared/base'
    - 'src/maskbook/packages/web3-shared/evm'
    - 'src/maskbook/packages/web3-shared/flow'
    - 'src/maskbook/packages/web3-shared/solana'
