/* cspell:disable */
import { ChainId } from '@masknet/web3-shared-evm';

export const DEBANK_CHAINS = [
    {
        id: 'eth',
        community_id: 1,
        name: 'Ethereum',
        native_token_id: 'eth',
        logo_url: 'https://static.debank.com/image/chain/logo_url/eth/42ba589cd077e7bdd97db6480b0ff61d.png',
    },
    {
        id: 'bsc',
        community_id: 56,
        name: 'BSC',
        native_token_id: 'bsc',
        logo_url: 'https://static.debank.com/image/chain/logo_url/bsc/7c87af7b52853145f6aa790d893763f1.png',
    },
    {
        id: 'xdai',
        community_id: 100,
        name: 'Gnosis',
        native_token_id: 'xdai',
        logo_url: 'https://static.debank.com/image/chain/logo_url/xdai/8b5320523b30bd57a388d1bcc775acd5.png',
    },
    {
        id: 'matic',
        community_id: 137,
        name: 'Polygon',
        native_token_id: 'matic',
        logo_url: 'https://static.debank.com/image/chain/logo_url/matic/d3d807aff1a13e9ba51a14ff153d6807.png',
    },
    {
        id: 'ftm',
        community_id: 250,
        name: 'Fantom',
        native_token_id: 'ftm',
        logo_url: 'https://static.debank.com/image/chain/logo_url/ftm/700fca32e0ee6811686d72b99cc67713.png',
    },
    {
        id: 'okt',
        community_id: 66,
        name: 'OEC',
        native_token_id: 'okt',
        logo_url: 'https://static.debank.com/image/chain/logo_url/okt/1228cd92320b3d33769bd08eecfb5391.png',
    },
    {
        id: 'heco',
        community_id: 128,
        name: 'HECO',
        native_token_id: 'heco',
        logo_url: 'https://static.debank.com/image/chain/logo_url/heco/db5152613c669e0cc8624d466d6c94ea.png',
    },
    {
        id: 'avax',
        community_id: 43114,
        name: 'Avalanche',
        native_token_id: 'avax',
        logo_url: 'https://static.debank.com/image/chain/logo_url/avax/4d1649e8a0c7dec9de3491b81807d402.png',
    },
    {
        id: 'op',
        community_id: 10,
        name: 'Optimism',
        native_token_id: 'op',
        logo_url: 'https://static.debank.com/image/chain/logo_url/op/01ae734fe781c9c2ae6a4cc7e9244056.png',
    },
    {
        id: 'arb',
        community_id: 42161,
        name: 'Arbitrum',
        native_token_id: 'arb',
        logo_url: 'https://static.debank.com/image/chain/logo_url/arb/f6d1b236259654d531a1459b2bccaf64.png',
    },
    {
        id: 'celo',
        community_id: 42220,
        name: 'Celo',
        native_token_id: 'celo',
        logo_url: 'https://static.debank.com/image/chain/logo_url/celo/41da5c1d3c0945ae822a1f85f02c76cf.png',
    },
    {
        id: 'movr',
        community_id: 1285,
        name: 'Moonriver',
        native_token_id: 'movr',
        logo_url: 'https://static.debank.com/image/chain/logo_url/movr/4b0de5a711b437f187c0d0f15cc0398b.png',
    },
    {
        id: 'cro',
        community_id: 25,
        name: 'Cronos',
        native_token_id: 'cro',
        logo_url: 'https://static.debank.com/image/chain/logo_url/cro/44f784a1f4c0ea7d26d00acabfdf0028.png',
    },
    {
        id: 'boba',
        community_id: 288,
        name: 'Boba',
        native_token_id: 'boba',
        logo_url: 'https://static.debank.com/image/chain/logo_url/boba/e43d79cd8088ceb3ea3e4a240a75728f.png',
    },
    {
        id: 'metis',
        community_id: 1088,
        name: 'Metis',
        native_token_id: 'metis',
        logo_url: 'https://static.debank.com/image/chain/logo_url/metis/b289da32db4d860ebf6fb46a6e41dcfc.png',
    },
    {
        id: 'btt',
        community_id: 199,
        name: 'BitTorrent',
        native_token_id: 'btt',
        logo_url: 'https://static.debank.com/image/chain/logo_url/btt/2130a8d57ff2a0f3d50a4ec9432897c6.png',
    },
    {
        id: 'aurora',
        community_id: 1313161554,
        name: 'Aurora',
        native_token_id: 'aurora',
        logo_url: 'https://static.debank.com/image/chain/logo_url/aurora/c7590fd2defb8e7d7dc071166838c33a.png',
    },
    {
        id: 'mobm',
        community_id: 1284,
        name: 'Moonbeam',
        native_token_id: 'mobm',
        logo_url: 'https://static.debank.com/image/chain/logo_url/mobm/a8442077d76b258297181c3e6eb8c9cc.png',
    },
    {
        id: 'sbch',
        community_id: 10000,
        name: 'SmartBch',
        native_token_id: 'sbch',
        logo_url: 'https://static.debank.com/image/chain/logo_url/sbch/d78ac780803e7f0a17b73558f423502e.png',
    },
    {
        id: 'fuse',
        community_id: 122,
        name: 'Fuse',
        native_token_id: 'fuse',
        logo_url: 'https://static.debank.com/image/chain/logo_url/fuse/ea4c9e12e7f646d42aa8fb07ab8dfec8.png',
    },
    {
        id: 'hmy',
        community_id: 1666600000,
        name: 'Harmony',
        native_token_id: 'hmy',
        logo_url: 'https://static.debank.com/image/chain/logo_url/hmy/734c003023531e31c636ae25d5a73172.png',
    },
    {
        id: 'klay',
        community_id: 8217,
        name: 'Klaytn',
        native_token_id: 'klay',
        logo_url: 'https://static.debank.com/image/chain/logo_url/klay/1df018b8493cb97c50b7e390ef63cba4.png',
    },
    {
        id: 'astar',
        community_id: 592,
        name: 'Astar',
        native_token_id: 'astar',
        logo_url: 'https://static.debank.com/image/chain/logo_url/astar/398c7e0014bdada3d818367a7273fabe.png',
    },
    {
        id: 'sdn',
        community_id: 336,
        name: 'Shiden',
        native_token_id: 'sdn',
        logo_url: 'https://static.debank.com/image/chain/logo_url/sdn/0baaa4ee7cb16feed71119b062ccd277.png',
    },
    {
        id: 'palm',
        community_id: 11297108109,
        name: 'Palm',
        native_token_id: 'palm',
        logo_url: 'https://static.debank.com/image/chain/logo_url/palm/ece828c59e643b8a8a13aa99145ae7d7.png',
    },
    {
        id: 'iotx',
        community_id: 4689,
        name: 'IoTeX',
        native_token_id: 'iotx',
        logo_url: 'https://static.debank.com/image/chain/logo_url/iotx/d3be2cd8677f86bd9ab7d5f3701afcc9.png',
    },
    {
        id: 'rsk',
        community_id: 30,
        name: 'RSK',
        native_token_id: 'rsk',
        logo_url: 'https://static.debank.com/image/chain/logo_url/rsk/2958b02ef823097b70fac99f39889e2e.png',
    },
    {
        id: 'wan',
        community_id: 888,
        name: 'Wanchain',
        native_token_id: 'wan',
        logo_url: 'https://static.debank.com/image/chain/logo_url/wan/f3aa8b31414732ea5e026e05665146e6.png',
    },
    {
        id: 'kcc',
        community_id: 321,
        name: 'KCC',
        native_token_id: 'kcc',
        logo_url: 'https://static.debank.com/image/chain/logo_url/kcc/3a5a4ef7d5f1db1e53880d70219d75b6.png',
    },
    {
        id: 'sgb',
        community_id: 19,
        name: 'Songbird',
        native_token_id: 'sgb',
        logo_url: 'https://static.debank.com/image/chain/logo_url/sgb/619f46d574d62a50bdfd9f0e2f47ddc1.png',
    },
    {
        id: 'evmos',
        community_id: 9001,
        name: 'EvmOS',
        native_token_id: 'evmos',
        logo_url: 'https://static.debank.com/image/chain/logo_url/evmos/26e038b4d5475d5a4b92f7fc08bdabc9.png',
    },
    {
        id: 'dfk',
        community_id: 53935,
        name: 'DFK',
        native_token_id: 'dfk',
        logo_url: 'https://static.debank.com/image/chain/logo_url/dfk/233867c089c5b71be150aa56003f3f7a.png',
    },
    {
        id: 'tlos',
        community_id: 40,
        name: 'Telos',
        native_token_id: 'tlos',
        logo_url: 'https://static.debank.com/image/chain/logo_url/telos/f9f7493def4c08ed222540bebd8ce87a.png',
    },
    {
        id: 'swm',
        community_id: 73772,
        name: 'Swimmer',
        native_token_id: 'swm',
        logo_url: 'https://static.debank.com/image/chain/logo_url/swm/361526e901cb506ef7074c3678ce769a.png',
    },
    {
        id: 'nova',
        community_id: 42170,
        name: 'Arbitrum Nova',
        native_token_id: 'nova',
        logo_url: 'https://static.debank.com/image/chain/logo_url/nova/06eb2b7add8ba443d5b219c04089c326.png',
    },
    {
        id: 'canto',
        community_id: 7700,
        name: 'Canto',
        native_token_id: 'canto',
        logo_url: 'https://static.debank.com/image/chain/logo_url/canto/47574ef619e057d2c6bbce1caba57fb6.png',
    },
    {
        id: 'doge',
        community_id: 2000,
        name: 'Dogechain',
        native_token_id: 'doge',
        logo_url: 'https://static.debank.com/image/chain/logo_url/doge/2538141079688a7a43bc22c7b60fb45f.png',
    },
    {
        id: 'kava',
        community_id: 2222,
        name: 'Kava',
        native_token_id: 'kava',
        logo_url: 'https://static.debank.com/image/chain/logo_url/step/a09a84faa6fc54a5c86dd41eccd4f9d1.png',
    },
    {
        id: 'step',
        community_id: 1234,
        name: 'Step',
        native_token_id: 'step',
        logo_url: 'https://static.debank.com/image/chain/logo_url/step/db79600b8feafe17845617ca9c606dbe.png',
    },
    {
        id: 'mada',
        community_id: 2001,
        name: 'Milkomeda',
        native_token_id: 'mada',
        logo_url: 'https://static.debank.com/image/chain/logo_url/mada/cdc4b1112c2c5a2757cbda33f4476b7f.png',
    },
    {
        id: 'cfx',
        community_id: 1030,
        name: 'Conflux',
        native_token_id: 'cfx',
        logo_url: 'https://static.debank.com/image/chain/logo_url/cfx/eab0c7304c6820b48b2a8d0930459b82.png',
    },
    {
        id: 'brise',
        community_id: 32520,
        name: 'Bitgert',
        native_token_id: 'brise',
        logo_url: 'https://static.debank.com/image/chain/logo_url/brise/4f6c040cf49f4d8c4eabbad7cd2f4ae4.png',
    },
];

export const DEBANK_CHAIN_TO_CHAIN_ID_MAP: Record<string, number> = {
    arb: ChainId.Arbitrum,
    astar: ChainId.Astar,
    aurora: ChainId.Aurora,
    avax: ChainId.Avalanche,
    boba: ChainId.Boba,
    brise: ChainId.Brise,
    bsc: ChainId.BSC,
    btt: ChainId.BitTorrent,
    canto: ChainId.Canto,
    celo: ChainId.Celo,
    cfx: ChainId.Conflux,
    cro: ChainId.Cronos,
    dfk: ChainId.DFK,
    doge: ChainId.Doge,
    eth: ChainId.Mainnet,
    evmos: ChainId.Evmos,
    ftm: ChainId.Fantom,
    fuse: ChainId.Fuse,
    heco: ChainId.HuobiEco,
    hmy: ChainId.Harmony,
    iotx: ChainId.IoTex,
    kava: ChainId.Kava,
    kcc: ChainId.Kcc,
    klay: ChainId.Klaytn,
    mada: ChainId.Milkomeda,
    matic: ChainId.Matic,
    metis: ChainId.Metis,
    mobm: ChainId.Moonbeam,
    movr: ChainId.Moonriver,
    nova: ChainId.Arbitrum_Nova,
    okt: ChainId.OKXChain,
    op: ChainId.Optimism,
    palm: ChainId.Palm,
    pls: ChainId.Pulse,
    rsk: ChainId.RSK,
    sbch: ChainId.SmartBitcoinCash,
    sdn: ChainId.Shiden,
    sgb: ChainId.SongbirdCanary,
    step: ChainId.Step,
    swm: 73772,
    tlos: ChainId.Telos,
    wan: ChainId.Wanchain,
    xdai: ChainId.xDai,
    base: ChainId.Base,
    scrl: ChainId.Scroll,
};
