/* cspell:disable */

export const DEBANK_CHAINS = [
    {
        id: 'eth',
        community_id: 1,
        name: 'Ethereum',
        native_token_id: 'eth',
    },
    {
        id: 'bsc',
        community_id: 56,
        name: 'BSC',
        native_token_id: 'bsc',
    },
    {
        id: 'xdai',
        community_id: 100,
        name: 'Gnosis',
        native_token_id: 'xdai',
    },
    {
        id: 'matic',
        community_id: 137,
        name: 'Polygon',
        native_token_id: 'matic',
    },
    {
        id: 'ftm',
        community_id: 250,
        name: 'Fantom',
        native_token_id: 'ftm',
    },
    {
        id: 'okt',
        community_id: 66,
        name: 'OEC',
        native_token_id: 'okt',
    },
    {
        id: 'heco',
        community_id: 128,
        name: 'HECO',
        native_token_id: 'heco',
    },
    {
        id: 'avax',
        community_id: 43114,
        name: 'Avalanche',
        native_token_id: 'avax',
    },
    {
        id: 'op',
        community_id: 10,
        name: 'Optimism',
        native_token_id: 'op',
    },
    {
        id: 'arb',
        community_id: 42161,
        name: 'Arbitrum',
        native_token_id: 'arb',
    },
    {
        id: 'celo',
        community_id: 42220,
        name: 'Celo',
        native_token_id: 'celo',
    },
    {
        id: 'movr',
        community_id: 1285,
        name: 'Moonriver',
        native_token_id: 'movr',
    },
    {
        id: 'cro',
        community_id: 25,
        name: 'Cronos',
        native_token_id: 'cro',
    },
    {
        id: 'boba',
        community_id: 288,
        name: 'Boba',
        native_token_id: 'boba',
    },
    {
        id: 'metis',
        community_id: 1088,
        name: 'Metis',
        native_token_id: 'metis',
    },
    {
        id: 'btt',
        community_id: 199,
        name: 'BitTorrent',
        native_token_id: 'btt',
    },
    {
        id: 'aurora',
        community_id: 1313161554,
        name: 'Aurora',
        native_token_id: 'aurora',
    },
    {
        id: 'mobm',
        community_id: 1284,
        name: 'Moonbeam',
        native_token_id: 'mobm',
    },
    {
        id: 'sbch',
        community_id: 10000,
        name: 'SmartBch',
        native_token_id: 'sbch',
    },
    {
        id: 'fuse',
        community_id: 122,
        name: 'Fuse',
        native_token_id: 'fuse',
    },
    {
        id: 'hmy',
        community_id: 1666600000,
        name: 'Harmony',
        native_token_id: 'hmy',
    },
    {
        id: 'klay',
        community_id: 8217,
        name: 'Klaytn',
        native_token_id: 'klay',
    },
    {
        id: 'astar',
        community_id: 592,
        name: 'Astar',
        native_token_id: 'astar',
    },
    {
        id: 'sdn',
        community_id: 336,
        name: 'Shiden',
        native_token_id: 'sdn',
    },
    {
        id: 'palm',
        community_id: 11297108109,
        name: 'Palm',
        native_token_id: 'palm',
    },
    {
        id: 'iotx',
        community_id: 4689,
        name: 'IoTeX',
        native_token_id: 'iotx',
    },
    {
        id: 'rsk',
        community_id: 30,
        name: 'RSK',
        native_token_id: 'rsk',
    },
    {
        id: 'wan',
        community_id: 888,
        name: 'Wanchain',
        native_token_id: 'wan',
    },
    {
        id: 'kcc',
        community_id: 321,
        name: 'KCC',
        native_token_id: 'kcc',
    },
    {
        id: 'sgb',
        community_id: 19,
        name: 'Songbird',
        native_token_id: 'sgb',
    },
    {
        id: 'evmos',
        community_id: 9001,
        name: 'EvmOS',
        native_token_id: 'evmos',
    },
    {
        id: 'dfk',
        community_id: 53935,
        name: 'DFK',
        native_token_id: 'dfk',
    },
    {
        id: 'tlos',
        community_id: 40,
        name: 'Telos',
        native_token_id: 'tlos',
    },
    {
        id: 'swm',
        community_id: 73772,
        name: 'Swimmer',
        native_token_id: 'swm',
    },
    {
        id: 'nova',
        community_id: 42170,
        name: 'Arbitrum Nova',
        native_token_id: 'nova',
    },
    {
        id: 'canto',
        community_id: 7700,
        name: 'Canto',
        native_token_id: 'canto',
    },
    {
        id: 'doge',
        community_id: 2000,
        name: 'Dogechain',
        native_token_id: 'doge',
    },
    {
        id: 'kava',
        community_id: 2222,
        name: 'Kava',
        native_token_id: 'kava',
    },
    {
        id: 'step',
        community_id: 1234,
        name: 'Step',
        native_token_id: 'step',
    },
    {
        id: 'mada',
        community_id: 2001,
        name: 'Milkomeda',
        native_token_id: 'mada',
    },
    {
        id: 'cfx',
        community_id: 1030,
        name: 'Conflux',
        native_token_id: 'cfx',
    },
    {
        id: 'brise',
        community_id: 32520,
        name: 'Bitgert',
        native_token_id: 'brise',
    },
];
