/* cspell:disable */
export const MirrorABI = [
    {
        inputs: [
            { internalType: 'address', name: '_factory', type: 'address' },
            { internalType: 'address', name: '_treasuryConfiguration', type: 'address' },
            { internalType: 'address', name: '_o11y', type: 'address' },
        ],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    { inputs: [], name: 'InvalidCreator', type: 'error' },
    { inputs: [], name: 'InvalidCreatorAttributionSignature', type: 'error' },
    { inputs: [], name: 'InvalidShortString', type: 'error' },
    { inputs: [], name: 'NameAndVersionTooLong', type: 'error' },
    { inputs: [{ internalType: 'string', name: 'str', type: 'string' }], name: 'StringTooLong', type: 'error' },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'approved', type: 'address' },
            { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        ],
        name: 'Approval',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'operator', type: 'address' },
            { indexed: false, internalType: 'bool', name: 'approved', type: 'bool' },
        ],
        name: 'ApprovalForAll',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'string', name: 'oldBaseDescriptionURI', type: 'string' },
            { indexed: false, internalType: 'string', name: 'newBaseDescriptionURI', type: 'string' },
        ],
        name: 'BaseDescriptionURISet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
        ],
        name: 'CloneDeployed',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'bytes32', name: 'structHash', type: 'bytes32' },
            { indexed: false, internalType: 'string', name: 'domainName', type: 'string' },
            { indexed: false, internalType: 'string', name: 'version', type: 'string' },
            { indexed: false, internalType: 'address', name: 'creator', type: 'address' },
            { indexed: false, internalType: 'bytes', name: 'signature', type: 'bytes' },
        ],
        name: 'CreatorAttribution',
        type: 'event',
    },
    { anonymous: false, inputs: [], name: 'EIP712DomainChanged', type: 'event' },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'bool', name: 'guard', type: 'bool' }],
        name: 'FactoryGuardSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: true, internalType: 'address', name: 'oldImplementation', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newImplementation', type: 'address' },
        ],
        name: 'FactoryImplementationSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldLimit', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'newLimit', type: 'uint256' },
        ],
        name: 'FactoryLimitSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'oldFundingRecipient', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newFundingRecipient', type: 'address' },
        ],
        name: 'FundingRecipientSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
        ],
        name: 'OwnershipTransferred',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldLimit', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'newLimit', type: 'uint256' },
        ],
        name: 'PriceSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' }],
        name: 'PriceSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'renderer', type: 'address' },
        ],
        name: 'RendererSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: true, internalType: 'address', name: 'renderer', type: 'address' }],
        name: 'RendererSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'creatorReward', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'mintReferralReward', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'firstMinterReward', type: 'uint256' },
            { indexed: false, internalType: 'address', name: 'creator', type: 'address' },
            { indexed: false, internalType: 'address', name: 'mintReferral', type: 'address' },
            { indexed: false, internalType: 'address', name: 'firstMinter', type: 'address' },
        ],
        name: 'RewardsDistributed',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'oldRoyaltyRecipient', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldRoyaltyBPS', type: 'uint256' },
            { indexed: true, internalType: 'address', name: 'newRoyaltyRecipient', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'newRoyaltyBPS', type: 'uint256' },
        ],
        name: 'RoyaltyChange',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'oldRoyaltyRecipient', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldRoyaltyBPS', type: 'uint256' },
            { indexed: true, internalType: 'address', name: 'newRoyaltyRecipient', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'newRoyaltyBPS', type: 'uint256' },
        ],
        name: 'RoyaltyChange',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'from', type: 'address' },
            { indexed: true, internalType: 'address', name: 'to', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        ],
        name: 'Transfer',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'from', type: 'address' },
            { indexed: true, internalType: 'address', name: 'to', type: 'address' },
            { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        ],
        name: 'Transfer',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'address', name: 'oldTributary', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newTributary', type: 'address' },
        ],
        name: 'TributarySet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldLimit', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'newLimit', type: 'uint256' },
        ],
        name: 'WritingEditionLimitSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'oldLimit', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'newLimit', type: 'uint256' },
        ],
        name: 'WritingEditionLimitSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
            { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
            { indexed: false, internalType: 'string', name: 'message', type: 'string' },
            { indexed: false, internalType: 'uint256', name: 'flatFeeAmount', type: 'uint256' },
        ],
        name: 'WritingEditionPurchased',
        type: 'event',
    },
    {
        inputs: [],
        name: 'TYPEHASH',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'VERSION',
        outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'acceptOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        ],
        name: 'approve',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
        name: 'balanceOf',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'baseDescriptionURI',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'cancelOwnershipTransfer', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [],
        name: 'contentURI',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'contractURI',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'description',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'eip712Domain',
        outputs: [
            { internalType: 'bytes1', name: 'fields', type: 'bytes1' },
            { internalType: 'string', name: 'name', type: 'string' },
            { internalType: 'string', name: 'version', type: 'string' },
            { internalType: 'uint256', name: 'chainId', type: 'uint256' },
            { internalType: 'address', name: 'verifyingContract', type: 'address' },
            { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
            { internalType: 'uint256[]', name: 'extensions', type: 'uint256[]' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'factory',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'firstMinter',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'fundingRecipient',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
        name: 'getApproved',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'guardOn',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'imageURI',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: '_creator', type: 'address' },
            {
                components: [
                    { internalType: 'string', name: 'name', type: 'string' },
                    { internalType: 'string', name: 'symbol', type: 'string' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'string', name: 'imageURI', type: 'string' },
                    { internalType: 'string', name: 'contentURI', type: 'string' },
                    { internalType: 'uint256', name: 'price', type: 'uint256' },
                    { internalType: 'uint256', name: 'limit', type: 'uint256' },
                    { internalType: 'address', name: 'fundingRecipient', type: 'address' },
                    { internalType: 'address', name: 'renderer', type: 'address' },
                    { internalType: 'uint256', name: 'nonce', type: 'uint256' },
                ],
                internalType: 'struct IWritingEditions.WritingEdition',
                name: 'edition',
                type: 'tuple',
            },
            { internalType: 'address', name: 'tokenRecipient', type: 'address' },
            { internalType: 'string', name: 'message', type: 'string' },
            { internalType: 'address', name: 'mintReferral', type: 'address' },
            { internalType: 'bool', name: '_guardOn', type: 'bool' },
        ],
        name: 'initialize',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: '_creator', type: 'address' },
            { internalType: 'bytes32', name: 'structHash', type: 'bytes32' },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
            {
                components: [
                    { internalType: 'string', name: 'name', type: 'string' },
                    { internalType: 'string', name: 'symbol', type: 'string' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'string', name: 'imageURI', type: 'string' },
                    { internalType: 'string', name: 'contentURI', type: 'string' },
                    { internalType: 'uint256', name: 'price', type: 'uint256' },
                    { internalType: 'uint256', name: 'limit', type: 'uint256' },
                    { internalType: 'address', name: 'fundingRecipient', type: 'address' },
                    { internalType: 'address', name: 'renderer', type: 'address' },
                    { internalType: 'uint256', name: 'nonce', type: 'uint256' },
                ],
                internalType: 'struct IWritingEditions.WritingEdition',
                name: 'edition',
                type: 'tuple',
            },
            { internalType: 'address', name: 'tokenRecipient', type: 'address' },
            { internalType: 'string', name: 'message', type: 'string' },
            { internalType: 'address', name: 'mintReferral', type: 'address' },
            { internalType: 'bool', name: '_guardOn', type: 'bool' },
            { internalType: 'address', name: 'sender', type: 'address' },
        ],
        name: 'initializeWithSignature',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'owner', type: 'address' },
            { internalType: 'address', name: 'operator', type: 'address' },
        ],
        name: 'isApprovedForAll',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'isNextOwner',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'isOwner',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'limit',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'tokenRecipient', type: 'address' }],
        name: 'mint',
        outputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'name',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'o11y',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' }],
        name: 'ownerOf',
        outputs: [{ internalType: 'address[]', name: 'owners', type: 'address[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
        name: 'ownerOf',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'packedDomainNameAndVersion',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'price',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'tokenRecipient', type: 'address' },
            { internalType: 'string', name: 'message', type: 'string' },
            { internalType: 'address', name: 'mintReferral', type: 'address' },
        ],
        name: 'purchase',
        outputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'renderer',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [],
        name: 'royaltyBPS',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
            { internalType: 'uint256', name: '_salePrice', type: 'uint256' },
        ],
        name: 'royaltyInfo',
        outputs: [
            { internalType: 'address', name: 'receiver', type: 'address' },
            { internalType: 'uint256', name: 'royaltyAmount', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'royaltyRecipient',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'from', type: 'address' },
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        ],
        name: 'safeTransferFrom',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'from', type: 'address' },
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
            { internalType: 'bytes', name: '_data', type: 'bytes' },
        ],
        name: 'safeTransferFrom',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'operator', type: 'address' },
            { internalType: 'bool', name: 'approved', type: 'bool' },
        ],
        name: 'setApprovalForAll',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'string', name: 'newBaseDescriptionURI', type: 'string' }],
        name: 'setBaseDescriptionURI',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_fundingRecipient', type: 'address' }],
        name: 'setFundingRecipient',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'newLimit', type: 'uint256' }],
        name: 'setLimit',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [], name: 'setMaxLimit', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'uint256', name: '_price', type: 'uint256' }],
        name: 'setPrice',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_renderer', type: 'address' }],
        name: 'setRenderer',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'royaltyRecipient_', type: 'address' },
            { internalType: 'uint256', name: 'royaltyBPS_', type: 'uint256' },
        ],
        name: 'setRoyaltyInfo',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
        name: 'supportsInterface',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'pure',
        type: 'function',
    },
    {
        inputs: [],
        name: 'symbol',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'toggleGuard', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
        name: 'tokenURI',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'totalSupply',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'from', type: 'address' },
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        ],
        name: 'transferFrom',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'nextOwner_', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'treasuryConfiguration',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
];

export const MirrorFactoryABI = [
    {
        inputs: [
            { internalType: 'address', name: '_owner', type: 'address' },
            { internalType: 'address', name: '_treasuryConfiguration', type: 'address' },
            { internalType: 'address', name: '_o11y', type: 'address' },
            { internalType: 'uint256', name: '_maxLimit', type: 'uint256' },
            { internalType: 'bool', name: '_guardOn', type: 'bool' },
        ],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'string', name: 'oldBaseDescriptionURI', type: 'string' },
            { indexed: false, internalType: 'string', name: 'newBaseDescriptionURI', type: 'string' },
        ],
        name: 'BaseDescriptionURISet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
        ],
        name: 'CloneDeployed',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'implementation', type: 'address' },
        ],
        name: 'EditionsDeployed',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'bool', name: 'guard', type: 'bool' }],
        name: 'FactoryGuardSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: true, internalType: 'address', name: 'oldImplementation', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newImplementation', type: 'address' },
        ],
        name: 'FactoryImplementationSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldLimit', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'newLimit', type: 'uint256' },
        ],
        name: 'FactoryLimitSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'oldFundingRecipient', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newFundingRecipient', type: 'address' },
        ],
        name: 'FundingRecipientSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'oldImplementation', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newImplementation', type: 'address' },
        ],
        name: 'NewImplementation',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
        ],
        name: 'OwnershipTransferred',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldLimit', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'newLimit', type: 'uint256' },
        ],
        name: 'PriceSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'renderer', type: 'address' },
        ],
        name: 'RendererSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'oldRoyaltyRecipient', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldRoyaltyBPS', type: 'uint256' },
            { indexed: true, internalType: 'address', name: 'newRoyaltyRecipient', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'newRoyaltyBPS', type: 'uint256' },
        ],
        name: 'RoyaltyChange',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: true, internalType: 'address', name: 'from', type: 'address' },
            { indexed: true, internalType: 'address', name: 'to', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        ],
        name: 'Transfer',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'address', name: 'oldTributary', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newTributary', type: 'address' },
        ],
        name: 'TributarySet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'oldLimit', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'newLimit', type: 'uint256' },
        ],
        name: 'WritingEditionLimitSet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'clone', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
            { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
            { indexed: false, internalType: 'string', name: 'message', type: 'string' },
            { indexed: false, internalType: 'uint256', name: 'flatFeeAmount', type: 'uint256' },
        ],
        name: 'WritingEditionPurchased',
        type: 'event',
    },
    {
        inputs: [],
        name: 'VERSION',
        outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'acceptOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [],
        name: 'baseDescriptionURI',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'cancelOwnershipTransfer', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [
            {
                components: [
                    { internalType: 'string', name: 'name', type: 'string' },
                    { internalType: 'string', name: 'symbol', type: 'string' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'string', name: 'imageURI', type: 'string' },
                    { internalType: 'string', name: 'contentURI', type: 'string' },
                    { internalType: 'uint256', name: 'price', type: 'uint256' },
                    { internalType: 'uint256', name: 'limit', type: 'uint256' },
                    { internalType: 'address', name: 'fundingRecipient', type: 'address' },
                    { internalType: 'address', name: 'renderer', type: 'address' },
                    { internalType: 'uint256', name: 'nonce', type: 'uint256' },
                ],
                internalType: 'struct IWritingEditions.WritingEdition',
                name: 'edition',
                type: 'tuple',
            },
        ],
        name: 'create',
        outputs: [{ internalType: 'address', name: 'clone', type: 'address' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'owner', type: 'address' },
            {
                components: [
                    { internalType: 'string', name: 'name', type: 'string' },
                    { internalType: 'string', name: 'symbol', type: 'string' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'string', name: 'imageURI', type: 'string' },
                    { internalType: 'string', name: 'contentURI', type: 'string' },
                    { internalType: 'uint256', name: 'price', type: 'uint256' },
                    { internalType: 'uint256', name: 'limit', type: 'uint256' },
                    { internalType: 'address', name: 'fundingRecipient', type: 'address' },
                    { internalType: 'address', name: 'renderer', type: 'address' },
                    { internalType: 'uint256', name: 'nonce', type: 'uint256' },
                ],
                internalType: 'struct IWritingEditions.WritingEdition',
                name: 'edition',
                type: 'tuple',
            },
            { internalType: 'uint8', name: 'v', type: 'uint8' },
            { internalType: 'bytes32', name: 'r', type: 'bytes32' },
            { internalType: 'bytes32', name: 's', type: 'bytes32' },
            { internalType: 'address', name: 'tokenRecipient', type: 'address' },
            { internalType: 'string', name: 'message', type: 'string' },
            { internalType: 'address', name: 'mintReferral', type: 'address' },
        ],
        name: 'createWithSignature',
        outputs: [{ internalType: 'address', name: 'clone', type: 'address' }],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'guardOn',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'implementation',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'isNextOwner',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'isOwner',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'maxLimit',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'o11y',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: '_implementation', type: 'address' },
            { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
        ],
        name: 'predictDeterministicAddress',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        name: 'salts',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'bool', name: '_guardOn', type: 'bool' }],
        name: 'setGuard',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_implementation', type: 'address' }],
        name: 'setImplementation',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_maxLimit', type: 'uint256' }],
        name: 'setLimit',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'clone', type: 'address' },
            { internalType: 'address', name: '_tributary', type: 'address' },
        ],
        name: 'setTributary',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'nextOwner_', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'treasuryConfiguration',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
];
