name: "Conventional Commits"

on:
    pull_request:

permissions:
    pull-requests: write

jobs:
    main:
        name: validate
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  wip: true
