name: 'Conventional Commits'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - '!sync-submodule-changes'
      - '!l10n_crowdin_action'

jobs:
  main:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
