name: Crowdin Download

on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00

  # start via Actions tab in Github UI
  workflow_dispatch:

jobs:
  download-translations:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Download from Crowdin
      uses: crowdin/github-action@1
      with:
        upload_translations: false
        download_translations: true
        create_pull_request: true
        pull_request_body: 'MF-0000'
        pull_request_base_branch_name: 'main'
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

