name: Draft Release Pull Request

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release: major, minor, or patch'
        required: false
        default: 'patch'

jobs:
  draft-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # 0 indicates all history for all branches and tags
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'

      - name: Get current version
        id: version
        run: echo "current_version=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          release_type="${{ github.event.inputs.release_type }}"
          if [ "$release_type" = "major" ]; then
            npm version major --git-tag-version false
          elif [ "$release_type" = "minor" ]; then
            npm version minor --git-tag-version false
          else
            npm version patch --git-tag-version false
          fi
          echo "new_version=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV

      - name: Commit and Push changes
        run: |
          git add package.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: bump version to ${{ env.new_version }}"
          git checkout -b 'bump-version-${{ env.new_version }}'
          git push origin 'bump-version-${{ env.new_version }}' -f
          git fetch

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'bump-version-${{ env.new_version }}'
          title: |
            ${{ github.event.inputs.release_type == 'major' && '[Release] New release ' || github.event.inputs.release_type == 'minor' && '[Release] New release ' || '[Release] Hotfix ' }}${{ env.version }} => ${{ env.new_version }} ${{ github.event.inputs.release_type == 'patch' && '(patch)' || github.event.inputs.release_type == 'minor' && '(minor)' || '(major)' }}
          body: 'Closes MF-0000'
          draft: true
          base: main
