name: Draft Release Pull Request

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release: major, minor, or patch'
        required: false
        default: 'patch'

jobs:
  draft-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'

      - name: Get current version
        id: version
        run: echo "current_version=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          release_type="${{ github.event.inputs.release_type }}"
          if [ "$release_type" = "major" ]; then
            npm version major
          elif [ "$release_type" = "minor" ]; then
            npm version minor
          else
            npm version patch
          fi
          echo "new_version=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Commit version bump
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version to ${{ env.new_version }}"

      - name: Push changes
        run: git push --set-upstream origin "bump-version-${{ env.new_version }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'bump-version-${{ env.new_version }}'
          title: |
            ${{ github.event.inputs.release_type == 'major' && '[Release] New release ' || github.event.inputs.release_type == 'minor' && '[Release] New release ' || '[Release] Hotfix ' }}${{ env.version }} => ${{ env.new_version }} ${{ github.event.inputs.release_type == 'patch' && '(patch)' || github.event.inputs.release_type == 'minor' && '(minor)' || '(major)' }}
          body: 'Closes MF-0000'
          base: main
