on:
  issues:
    types: [opened, edited]

jobs:
  decode-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        if: contains(github.event.issue.labels.*.name, 'decode-issue')
        with:
          script: |
            const { title, body } = context.payload.issue;
            const MARKER =  '<!-- decoded -->'
            if(!title.includes('%20') && !body.includes('%20')) {
              return;
            }
            if(body.includes(MARKER)) return;

            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: decodeURIComponent(title),
              body: decodeURIComponent(body) + MARKER
            })
