name: PR Issue Linker

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-linker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get PR description
      id: pr_description
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q ".body")
        echo "::set-output name=pr_body::${PR_BODY}"

    - name: Modify PR description with links
      id: modify_pr_description
      run: |
        # The regex to find the Jira issue (e.g., FW-xxxx), avoiding FW-0000
        PR_BODY="${{ steps.pr_description.outputs.pr_body }}"
        MODIFIED_BODY=$(echo "$PR_BODY" | sed -E 's/\bFW-([1-9][0-9]{3})\b/[FW-\1](https:\/\/mask.atlassian.net\/browse\/FW-\1)/g')
        echo "::set-output name=modified_pr_body::$MODIFIED_BODY"

    - name: Update PR description with modified content
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Update the PR description with the modified content
        gh pr edit ${{ github.event.pull_request.number }} --body "${{ steps.modify_pr_description.outputs.modified_pr_body }}"
