name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The next version to release, e.g. 0.1.0'
        required: true
        type: string
      release_kind:
        description: 'Select the release kind: major, minor, or patch'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Bump version
        id: bump_version
        run: |
          npm version ${{ inputs.release_kind }} --no-git-tag-version
          echo ::set-output name=NEW_VERSION::$(node -p "require('./package.json').version")
        
      - name: Commit version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "[Release] ${{ inputs.release_kind }} v${{ inputs.version }} => v${{ steps.bump_version.outputs.NEW_VERSION }}"
        
      - name: Tag version
        run: |
          git tag v${{ steps.bump_version.outputs.NEW_VERSION }}
        
      - name: Push version
        run: |
          git branch -f released
          git push origin released:released --force --tags
